10 A$ = "hello"
20 PRINT A$ ; " there"
30 IF "A" < "B" THEN PRINT "A < B"
40 IF "A" <= "B" THEN PRINT "A <= B"
50 IF "A" > "B" THEN PRINT "A > B"
60 IF "A" >= "B" THEN PRINT "A >= B"
70 IF A$ = "hello" THEN PRINT "A$ = hello"
80 IF A$ <> "hello" THEN PRINT "A$ <> hello"
90 PRINT A$ + " cat"
 