10 A = 1
20 B = 2
30 C = 3
40 D = 0.5
50 PRINT "A + B + C + D = " ; A + B + C + D
60 PRINT "A - B - C - D = " ; A - B - C - D
70 PRINT "A * B + C / D = " ; A * B + C / D
80 PRINT "(A * B) + (C / D) = " ; (A * B) + (C / D)
90 PRINT "A * (B + C) / D = " ; A * (B + C) / D
100 PRINT "A + B * C - D = " ; A + B * C - D
110 PRINT "A + (B * C) - D = " ; A + (B * C) - D
120 PRINT "(A + B) * (C - D) = " ; (A + B) * (C - D)
130 PRINT "-A + +B * -C - D = " ; -A + +B * -C - D
140 PRINT "-(A) + (+(B) * -(C)) - D = " ; -(A) + (+(B) * -(C)) - D
150 PRINT "(-A + +B) * -(C - D) = " ; (-A + +B) * -(C - D)
160 PRINT "A ^ B + C ^ D = " ; A ^ B + C ^ D
170 PRINT "(A ^ B) + (C ^ D) = " ; (A ^ B) + (C ^ D)
180 PRINT "A ^ (B + C) ^ D = " ; A ^ (B + C) ^ D
